/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_gestionvols (void);
GtkWidget* create_ajoutervol (void);
GtkWidget* create_modifiervol (void);
GtkWidget* create_Supprimervol (void);
GtkWidget* create_volreserver (void);
GtkWidget* create_modifiervol22 (void);
GtkWidget* create_ajouterRVOL (void);
GtkWidget* create_modifierres (void);
GtkWidget* create_supprimerres (void);
GtkWidget* create_clientres (void);
GtkWidget* create__ (void);
